### ISSUE TITLE
Login failed because web login url change

### ISSUE THREAD

**Issue by psa-jforestier** [outadoc/linkindle#8]
Unable to login to enedis :
linkpy.LinkyLoginException: Login unsuccessful. Check your credentials.

The hard coded logging LOGIN_BASE_URI is not working anymore.

**Comment by outadoc** [comment]
After some investigation, Enedis seems to have completely redone their customer-facing interface and the backing API recently. 🙁 

Without some hard work this seems like the end of the road. I would commit to that if there weren't similar projects available, which I would recommend switching to since they seem more widely used and maintained: cf. https://github.com/home-assistant/core/issues/33634

**Comment by psa-jforestier** [comment]
I'm also searching for other project, in any languages, but cant find something working (reversing a re-captcha code is too much work for my goals). An intermediate solution is to contact enedis via the websiste or twitter, and ask them why the open data are not open ? Hint : "yeah I undersatand, we are studing it but you know big company long decision blah blah"

**Comment by DRbuntu91** [comment]
Hello,
I use the Python file to retrieve every day my hourly electrical consumption (48 values) which I store then in an Excel file for later analysis. However this process stopped working on 1st July. After some searching I made the following changes in the file "__init__.py" and it started working again:
#LOGIN_BASE_URI = 'https://espace-client-connexion.enedis.fr'
LOGIN_BASE_URI = 'https://mon-compte-particulier.enedis.fr'
#API_BASE_URI = 'https://espace-client-particuliers.enedis.fr/group/espace-particuliers'
API_BASE_URI = 'https://mon-compte-particulier.enedis.fr/group/espace-particuliers'
PS: not sure this is a permanent solution but so for so good!

**Comment by outadoc** [comment]
@DRbuntu91 Thanks for your help! I tried your URLs but I still get a 404, strange.

**Comment by DRbuntu91** [comment]
Hello
I suppose this is a different error. Maybe a typo error somewhere?

I my case I was getting "Login Error : Login unsuccessful. Check your credentials." in the Python file at line 72 while my credentials were OK. I just rechecked right now and it still works....

**Comment by outadoc** [comment]
I get that same "Login unsuccessful" error, but it's caused by a 404 error when trying to login with `LOGIN_BASE_URI`, so it must be wrong... very strange!

**Comment by DRbuntu91** [comment]
But your regular login works at https://mon-compte-particulier.enedis.fr?

**Comment by outadoc** [comment]
Yep!

**Comment by DRbuntu91** [comment]
It still works for me. So today I have my hourly consumption of 30/6, 1/7, 2/7 and 3/7!

**Comment by vBlackOut** [comment]
hello, i have problem 404 what is your solution please if your are connected ?

**Comment by DRbuntu91** [comment]
Hello
It stopped working again on 8/7/2020 with the same error message I had en June (Login Error : Login unsuccessful. Check your credentials). Since then I'm unable to retrieve my hourly consumption....

**Comment by psa-jforestier** [comment]
Probably a refresh token has expired, or your account has been migrated to a new patform (with new features like "you cant access easily to your own data"). You should really contact Enedis about this (https://data.enedis.fr/page/contact/). The more requests they will have from personal end user, the more they will work on it. Next step : do a petition on change.org ?

**Comment by DRbuntu91** [comment]
Hello
The refresh of my "token" probably occurred because on 8th July I tried to collect my hourly consumption from a different location and thus with a different @IP. Since then it does not work any more (although I'm back home and I connected again via my web interface).
I wrote to Enedis and got back the following reply from opendata@enedis.fr: "Pour l’instant, les données de consommation individuelles ne sont pas disponibles via API pour les particuliers. Nous avons mis en place un service d’API pour les développeurs de service qui peut néanmoins vous intéresser : https://datahub-enedis.fr/data-connect/"

**Comment by sterrando** [comment]
Same here, blind since Jul 8th. That's really unfortunate as I was using your library to log consumption data since one year. I created an account on enedis Data-connect, but that looks awkward to me. For what concerns me, the solution will be an RF module connected to the teleinfo output on the meter itself.

**Comment by psa-jforestier** [comment]
>  do a petition on change.org ?

Please sign it : http://chng.it/HXnGHRX7cx
Sorry its in french.

**Comment by qdel** [comment]
Hi,

I just tried to open a "application" using this form: https://datahub-enedis.fr/data-connect/gerer-mon-service/creer-une-application/

For what i understand, i will need to implement this API:
https://datahub-enedis.fr/data-connect/documentation/authorize-v1/

And then i should have acces to these apis:
https://datahub-enedis.fr/data-connect/documentation/metering-data-v4/

For the moment i asked to create a "personnal application to access API and inject them to a grafana instance". Which is actually what i was doing.

Bad thing is this application need a redirect_uri to be implemented. So i think people will need a webserver and a domain name to make it work.

Depending of what Enedis says I will keep you tuned.

**Comment by roumano** [comment]
Hi,
Look like other python programmer found how to retrieve data with the new their customer-facing interface and the backing API recently : https://github.com/guillaumezin/DomoticzLinky/blob/master/plugin.py

Do you think it's can help to update your code ?

**Comment by outadoc** [comment]
> Do you think it's can help to update your code ?

Looking through what https://github.com/guillaumezin/DomoticzLinky managed to achieve both technically and administratively (signing actual consent forms with Enedis apparently!), I think it's time I officially stop maintaining this project and recommend switching to theirs. Pretty much everything has to be rewritten from scratch anyway, and @guillaumezin's repo provides so much more, I think it's worth migrating.

Thanks for your support and your efforts in restoring functionality, and sorry I couldn't do much more. :pray:
